stages:
  dvc_dependencies_analysis:
    cmd: python scripts/utils/compute_code_hashes.py
    always_changed: true
    outs:
      - .code_hash/

  download:
    cmd: python scripts/step_download.py --config-name dvc/step_download
    deps:
      - scripts/step_download.py
      - .code_hash/download.hash
      - configs/dataset/musique.yaml
    outs:
      - data/raw/musique_ans_v1.0_train.jsonl.metadata

  split:
    cmd: python scripts/step_split.py --config-name dvc/step_split
    deps:
      - scripts/step_split.py
      - .code_hash/split.hash
      - configs/dataset/musique.yaml
      - configs/config.yaml
      - data/raw/musique_ans_v1.0_train.jsonl.metadata
    outs:
      - data/processed/splits/musique/train.jsonl.metadata

  format:
    cmd: python scripts/step_format.py --config-name dvc/step_format
    deps:
      - scripts/step_format.py
      - .code_hash/format.hash
      - configs/dataset/musique.yaml
      - configs/config.yaml
      - data/processed/splits/musique/train.jsonl.metadata
    outs:
      - data/processed/colbert/musique/train.jsonl.metadata
      - data/processed/colbert/musique/validation.jsonl.metadata
      - data/processed/colbert/musique/test.jsonl.metadata
      - data/processed/hybrid/musique/train.jsonl.metadata
      - data/processed/hybrid/musique/validation.jsonl.metadata
      - data/processed/hybrid/musique/test.jsonl.metadata
      - data/processed/climb/musique/train.jsonl.metadata
      - data/processed/climb/musique/validation.jsonl.metadata
      - data/processed/climb/musique/test.jsonl.metadata

  train_colbert:
    cmd: python scripts/train_single.py --config-name dvc/train_colbert
    deps:
      - scripts/train_single.py
      - .code_hash/train_colbert.hash
      - configs/algo/colbert.yaml
      - data/processed/colbert/musique/train.jsonl.metadata
      - data/processed/colbert/musique/validation.jsonl.metadata
    outs:
      - models/finetuned/musique-colbert.metadata

  push_colbert:
    cmd: python scripts/step_push.py --config-name dvc/push_colbert
    deps:
      - scripts/step_push.py
      - .code_hash/push_colbert.hash
      - models/finetuned/musique-colbert.metadata

  train_hybrid:
    cmd: python scripts/train_single.py --config-name dvc/train_hybrid
    deps:
      - scripts/train_single.py
      - .code_hash/train_hybrid.hash
      - configs/algo/hybrid.yaml
      - data/processed/hybrid/musique/train.jsonl.metadata
      - data/processed/hybrid/musique/validation.jsonl.metadata
      - data/raw/musique_ans_v1.0_train.jsonl.metadata
    outs:
      - models/finetuned/musique-hybrid.metadata

  push_hybrid:
    cmd: python scripts/step_push.py --config-name dvc/push_hybrid
    deps:
      - scripts/step_push.py
      - .code_hash/push_hybrid.hash
      - models/finetuned/musique-hybrid.metadata

  train_mixer:
    cmd: python scripts/train_single.py --config-name dvc/train_mixer
    deps:
      - scripts/train_single.py
      - .code_hash/train_mixer.hash
      - configs/algo/mixer.yaml
      - data/processed/climb/musique/train.jsonl.metadata
      - data/processed/climb/musique/validation.jsonl.metadata
      - data/raw/musique_ans_v1.0_train.jsonl.metadata
    outs:
      - models/finetuned/musique-mixer.metadata

  push_mixer:
    cmd: python scripts/step_push.py --config-name dvc/push_mixer
    deps:
      - scripts/step_push.py
      - .code_hash/push_mixer.hash
      - models/finetuned/musique-mixer.metadata

  # Retrieval & Evaluation
  generate_candidates:
    cmd: python scripts/generate_candidates.py --config-name dvc/generate_candidates
    deps:
      - scripts/generate_candidates.py
      - .code_hash/generate_candidates.hash
      - configs/dvc/generate_candidates.yaml
      - data/processed/colbert/musique/train.jsonl.metadata
    outs:
      - data/candidates/musique_test.json.metadata

  # Intrinsic Evaluation Stages
  intrinsic_eval_colbert:
    cmd: python scripts/intrinsic_eval.py --config-name dvc/intrinsic_colbert
    deps:
      - scripts/intrinsic_eval.py
      - .code_hash/intrinsic_eval_colbert.hash
      - configs/dvc/intrinsic_colbert.yaml
      - models/finetuned/musique-colbert.metadata
    metrics:
      - results/intrinsic_eval_colbert.json:
          cache: true

  intrinsic_eval_hybrid:
    cmd: python scripts/intrinsic_eval.py --config-name dvc/intrinsic_hybrid
    deps:
      - scripts/intrinsic_eval.py
      - .code_hash/intrinsic_eval_hybrid.hash
      - configs/dvc/intrinsic_hybrid.yaml
      - models/finetuned/musique-hybrid.metadata
    metrics:
      - results/intrinsic_eval_hybrid.json:
          cache: true

  intrinsic_eval_climb:
    cmd: python scripts/intrinsic_eval.py --config-name dvc/intrinsic_climb
    deps:
      - scripts/intrinsic_eval.py
      - .code_hash/intrinsic_eval_climb.hash
      - configs/dvc/intrinsic_climb.yaml
      - models/finetuned/musique-mixer.metadata
    metrics:
      - results/intrinsic_eval_climb.json:
          cache: true

  # Benchmarking Stages
  benchmark_colbert:
    cmd: python scripts/benchmark.py --config-name dvc/benchmark_colbert
    deps:
      - scripts/benchmark.py
      - .code_hash/benchmark_colbert.hash
      - configs/dvc/benchmark_colbert.yaml
      - models/finetuned/musique-colbert.metadata
    metrics:
      - results/benchmark_colbert.json:
          cache: true

  benchmark_hybrid:
    cmd: python scripts/benchmark.py --config-name dvc/benchmark_hybrid
    deps:
      - scripts/benchmark.py
      - .code_hash/benchmark_hybrid.hash
      - configs/dvc/benchmark_hybrid.yaml
      - models/finetuned/musique-hybrid.metadata
      - data/candidates/musique_test.json.metadata
    metrics:
      - results/benchmark_hybrid.json:
          cache: true

  benchmark_climb:
    cmd: python scripts/benchmark.py --config-name dvc/benchmark_climb
    deps:
      - scripts/benchmark.py
      - .code_hash/benchmark_climb.hash
      - configs/dvc/benchmark_climb.yaml
      - models/finetuned/musique-mixer.metadata
      - data/candidates/musique_test.json.metadata
    metrics:
      - results/benchmark_climb.json:
          cache: true

  benchmark_bm25s:
    cmd: python scripts/benchmark.py --config-name dvc/benchmark_bm25s
    deps:
      - scripts/benchmark.py
      - .code_hash/benchmark_bm25s.hash
      - configs/dvc/benchmark_bm25s.yaml
    metrics:
      - results/benchmark_bm25s.json:
          cache: true

  benchmark_dense:
    cmd: python scripts/benchmark.py --config-name dvc/benchmark_dense
    deps:
      - scripts/benchmark.py
      - .code_hash/benchmark_dense.hash
      - configs/dvc/benchmark_dense.yaml
      - data/candidates/musique_test.json.metadata
    metrics:
      - results/benchmark_dense.json:
          cache: true

plots:
  - dvclive/plots/metrics/train/loss.tsv:
      template: linear
      x: step
      y: loss
      title: Training Loss
  - results/benchmark_musique_atomic.csv:
      template: bar_horizontal
      x: Algorithm
      y: NDCG@10
      title: Algorithm Comparison
